/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProdutoDto {

  /**
   * Indica se o produto está ativo
   */
  ativo?: boolean;

  /**
   * ID da cidade associada ao produto
   */
  cidadeId: number;

  /**
   * Timestamp da última atualização do produto
   */
  dataAtualizacao?: string;

  /**
   * Timestamp de criação do produto
   */
  dataCriacao?: string;

  /**
   * Descrição detalhada do produto
   */
  descricao?: string;

  /**
   * Quantidade de estoque do produto
   */
  estoque?: number;
  id?: number;

  /**
   * Nome do produto
   */
  nome: string;

  /**
   * Nome da cidade associada ao produto (apenas leitura)
   */
  nomeCidade?: string;

  /**
   * Código único do produto
   */
  sku: string;

  /**
   * Valor unitário do produto
   */
  valor: number;
}
