/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CidadeDto } from '../models/cidade-dto';
import { listarTodas } from '../fn/cidades/listar-todas';
import { ListarTodas$Params } from '../fn/cidades/listar-todas';


/**
 * Operações para gerenciamento de cidades
 */
@Injectable({ providedIn: 'root' })
export class CidadesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listarTodas()` */
  static readonly ListarTodasPath = '/v1/cidades';

  /**
   * Listar todas as cidades (disponível para USER e ADMIN).
   *
   * Retorna uma lista de todas as cidades. Requer autenticação JWT e role USER ou ADMIN.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarTodas()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarTodas$Response(params?: ListarTodas$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CidadeDto>>> {
    return listarTodas(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar todas as cidades (disponível para USER e ADMIN).
   *
   * Retorna uma lista de todas as cidades. Requer autenticação JWT e role USER ou ADMIN.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarTodas$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarTodas(params?: ListarTodas$Params, context?: HttpContext): Observable<Array<CidadeDto>> {
    return this.listarTodas$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CidadeDto>>): Array<CidadeDto> => r.body)
    );
  }

}
