/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProdutoDto as ComGestaoprodutosDtoProdutoDto } from '../../../../../../../../models/com/gestaoprodutos/dto/produto-dto';
import { PageableObject } from '../../../../../../../../models/pageable-object';
import { SortObject } from '../../../../../../../../models/sort-object';
export interface ProdutoDto {
  content?: Array<ComGestaoprodutosDtoProdutoDto>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}
