
FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=cFfHhJTpWr5t8kLmZq3t6w3y6B8DbGdJfNjQmSqVs
ENV MYSQL_DATABASE=nm_gestao_de_produtos
ENV MYSQL_USER=spring_boot_user
ENV MYSQL_PASSWORD=gNrPnTpWr5t8vA9DcF8DbGdJffHhJkLmZq3t6w

EXPOSE 3401

VOLUME /var/lib/mysql

CMD ["mysqld"]