/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CidadeDto } from '../../models/cidade-dto';

export interface ListarTodas$Params {
}

export function listarTodas(http: HttpClient, rootUrl: string, params?: ListarTodas$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CidadeDto>>> {
  const rb = new RequestBuilder(rootUrl, listarTodas.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CidadeDto>>;
    })
  );
}

listarTodas.PATH = '/v1/cidades';
