/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Representação dos dados de uma cidade
 */
export interface CidadeDto {

  /**
   * Timestamp da última atualização da cidade
   */
  dataAtualizacao?: string;

  /**
   * Timestamp de criação da cidade
   */
  dataCriacao?: string;

  /**
   * Sigla do estado (ex: SP, RJ)
   */
  estado?: string;

  /**
   * ID único da cidade
   */
  id?: number;

  /**
   * Nome da cidade
   */
  nome: string;
}
