/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados para criar um novo produto
 */
export interface ProdutoCreateRequest {

  /**
   * ID da cidade onde o produto está disponível
   */
  cidadeId: number;

  /**
   * Descrição detalhada do produto
   */
  descricao?: string;

  /**
   * Quantidade de estoque inicial do produto
   */
  estoque?: number;

  /**
   * Nome do produto
   */
  nome: string;

  /**
   * Código único do produto (SKU)
   */
  sku?: string;

  /**
   * Valor unitário do produto
   */
  valor: number;
}
