/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Usuario {
  admin?: boolean;
  cpf: string;
  dataAtualizacao?: string;
  dataCriacao?: string;
  email: string;
  id?: number;
  nome: string;
  role?: 'ADMIN' | 'USER';
  senha: string;
}
