/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProdutoDto as ComGestaoprodutosDtoProdutoDto } from '../../models/com/gestaoprodutos/dto/produto-dto';

export interface AtualizarProduto$Params {
  id: number;
      body: ComGestaoprodutosDtoProdutoDto
}

export function atualizarProduto(http: HttpClient, rootUrl: string, params: AtualizarProduto$Params, context?: HttpContext): Observable<StrictHttpResponse<ComGestaoprodutosDtoProdutoDto>> {
  const rb = new RequestBuilder(rootUrl, atualizarProduto.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ComGestaoprodutosDtoProdutoDto>;
    })
  );
}

atualizarProduto.PATH = '/v1/produtos/{id}';
