/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProdutoDto as ComGestaoprodutosDtoProdutoDto } from '../../models/com/gestaoprodutos/dto/produto-dto';

export interface BuscarPorId$Params {
  id: number;
}

export function buscarPorId(http: HttpClient, rootUrl: string, params: BuscarPorId$Params, context?: HttpContext): Observable<StrictHttpResponse<ComGestaoprodutosDtoProdutoDto>> {
  const rb = new RequestBuilder(rootUrl, buscarPorId.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ComGestaoprodutosDtoProdutoDto>;
    })
  );
}

buscarPorId.PATH = '/v1/produtos/{id}';
