/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CidadeDto } from './models/cidade-dto';
export type { ProdutoDto as ComGestaoprodutosDtoProdutoDto } from './models/com/gestaoprodutos/dto/produto-dto';
export type { LoginRequest as ComGestaoprodutosDtoRequestLoginRequest } from './models/com/gestaoprodutos/dto/request/login-request';
export type { RegisterRequest as ComGestaoprodutosDtoRequestRegisterRequest } from './models/com/gestaoprodutos/dto/request/register-request';
export type { JwtResponse as ComGestaoprodutosDtoResponseJwtResponse } from './models/com/gestaoprodutos/dto/response/jwt-response';
export type { Usuario as ComGestaoprodutosModelEntityUsuario } from './models/com/gestaoprodutos/model/entity/usuario';
export type { ProdutoDto as OrgSpringframeworkDataDomainPageComGestaoprodutosDtoProdutoDto } from './models/org/springframework/data/domain/PageCom/gestaoprodutos/dto/produto-dto';
export type { PageableObject } from './models/pageable-object';
export type { ProdutoCreateRequest } from './models/produto-create-request';
export type { SortObject } from './models/sort-object';
