/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ProdutosService } from './services/produtos.service';
export { AutenticacaoService } from './services/autenticacao.service';
export { CidadesService } from './services/cidades.service';
